sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: NPgsALb4XU2HoMwmls+dDS0S2SK6Xf3c3L8zhPVvrhkSXaJSu7g5EHquNnoBlT9sBLnD3BO5ZCPe9hNR3NErymizLP7EKC6wKXyHFSn9Z6T0q460p28R2H7UCsWSiXcF87z9fbBUBqGuyQER38KBg4sCu5+pGfw/ExQ4cl9eBLUARBbp1ZfVQH6NmNeE2exWmwaqIksQ6/IKNIN/XkiJw1fSy5N5oV2n9/gI+i71eJ4Eb6v0WtHAIMv9PL9RrrLlTyv7M6Q48HMB1rdA5DHVhndjhmqElIYIcU3+Z1zztkxF/dG6zASRMHCWprNLTwG6pMptO2+md2bJoH+n9GbJ7JFjJoKxC3IssVHawzZG85jPrih7y7Bl2oYj1JYd3A7UYio9K1O+Z6ZgSg4jK7OEr+df/CEl7r+XBMPV/s6r8+htxDiK/gzH6fLq2uT9qxjR6Rp+i9JjsSghmlHEnXYHXSfFa40ArAqC19s0pmTOLzEODa4Qnx09XWqdXXr0Gu21zV8QTfFN/A30+NMYXFzA1wSOTpr3fkUPSAcDN8pdnjHM0ooe0qdRs1KvWSTcOU6RyydJdKh9I4MR9LJKYdpyK9czgOsE2PxE0s72NIgA0P62qofg6nVMSKx1WcSRgeQKIeLBqWB4K1g0lQU4H/hxWnLV9BYJglmZt+zSBps9Gb4=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Corporation-of-London-Its-Rights-and-Privileges_5609
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy